name: Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      config: 'Release'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"
          dotnet-quality: "validated"
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration $config --no-restore
      - name: Test PR      
        run: dotnet test --no-restore --no-build --configuration $config
