name: Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '8.6.5'
          cabal-version: '2.4.0.0'
      - name: Run Tests
        run: cabal test
      - name: Check no changes
        run: git diff-files -p --exit-code --diff-filter=ADMR -w
      
